{% set name = "gmprocess" %}
{% set version = "2.5.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gmprocess-{{ version }}.tar.gz
  sha256: 5294c6c6ad893cc0b0840550cca38ac5dfa015076de56c21be2508be707e9d2d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - gmconvert = gmprocess.bin.gmconvert:main
    - gminfo = gmprocess.bin.gminfo:cli
    - gmrecords = gmprocess.bin.gmrecords:main
    - gmworkspace = gmprocess.bin.gmworkspace:main
    - gmprocess_config = gmprocess.bin.gmprocess_config:main
    - cwa_gather = gmprocess.bin.cwa_gather:cli
    - fix_inventory = gmprocess.bin.fix_inventory:main
    - fetch_orfeus = gmprocess.bin.fetch_orfeus:cli

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - setuptools-scm >=3.4
    - pip
    - numpy
    - wheel
  run:
    - pint >0.24.3
    - tqdm >4.67
    - python >={{ python_min }}
    - beautifulsoup4 >=4.11.0
    - configobj >=5.0.6
    - esi-core >=1.0.1
    - esi-utils-colors >1.0
    - esi-utils-io >1.0
    - esi-utils-rupture >1.0,<=1.0.4
    - folium >=0.12
    - gmpacket >=0.1.6
    - h5py >=3.11
    - lxml >=4.6.1
    - matplotlib-base >=3.1.0
    - numba >=0.58
    - numpy >=1.21,<2.0
    - obspy >=1.4.1
    - openpyxl >=3.0.8
    - openquake.engine >=3.18
    - pandas >=1.0
    - pint >0.24.3
    - ps2ff >=1.5.2
    - pyasdf >=0.7
    - pydantic >=2.0
    - requests >=2.29
    - ruamel.yaml >=0.17.16
    - schema >=0.7
    - scipy >=1.7
    - setuptools-scm >=6.3.2
    - statsmodels >=0.12.2
    - tqdm >4.67
    - usgs-strec >=2.3.11
    - xlrd >=2.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - gmprocess
  commands:
    - gmconvert --help
    - gminfo --help
    - gmrecords --version
    - gmworkspace --help
    - gmprocess_config --help
    - cwa_gather --help
    - fetch_orfeus --help

about:
  home: https://code.usgs.gov/ghsc/esi/groundmotion-processing
  license: LicenseRef-PublicDomain
  summary: Parsing and processing ground motion data.
  license_family: Public Domain
  license_file: LICENSE.md
  dev_url: https://code.usgs.gov/ghsc/esi/groundmotion-processing
  doc_url: https://ghsc.code-pages.usgs.gov/esi/groundmotion-processing/

extra:
  recipe-maintainers:
    - ocefpaf
    - mhearne-usgs
    - cbworden
    - emthompson-usgs
