{% set name = "gmprocess" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gmprocess-{{ version }}.tar.gz
  sha256: e90d36f85b16c31b8d0489d58baab3b086191897e9d66c01cbc4fbce20355fa7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - gmconvert = gmprocess.bin.gmconvert:main
    - gminfo = gmprocess.bin.gminfo:main
    - gmrecords = gmprocess.bin.gmrecords:main
    - gmworkspace = gmprocess.bin.gmworkspace:main
    - list_metrics = gmprocess.bin.list_metrics:main
    - cwb_gather = gmprocess.bin.cwb_gather:main

requirements:
  host:
    - python >=3.8,<3.11
    - setuptools >=42
    - setuptools-scm >=3.4
    - pip
    - numpy
    - wheel
  run:
    - pydantic >=2.0
    - python >=3.8,<3.11
    - beautifulsoup4 >=4.11.0
    - configobj >=5.0.6
    - esi-core >=1.0.1
    - esi-utils-colors >1.0
    - esi-utils-io >1.0
    - esi-utils-rupture >1.0
    - folium >=0.12
    - gmpacket >=0.1.6
    - h5py >=2.8
    - lxml >=4.6.1
    - matplotlib-base >=3.1.0
    - numpy >=1.21,<2.0
    - obspy >=1.4.0
    - openpyxl >=3.0.8
    - openquake.engine >=3.14
    - pandas >=1.0
    - ps2ff >=1.5.2
    - pyasdf >=0.7
    - requests >=2.29
    - ruamel.yaml >=0.17.16
    - schema >=0.7
    - scipy >=1.7
    - setuptools-scm >=6.3.2
    - statsmodels >=0.12.2
    - usgs-strec >=2.3.2
    - xlrd >=2.0

test:
  imports:
    - gmprocess
  commands:
    - gminfo --help

about:
  home: https://code.usgs.gov/ghsc/esi/groundmotion-processing
  license: LicenseRef-PublicDomain
  summary: Parsing and processing ground motion data.
  license_family: Public Domain
  license_file: LICENSE.md
  dev_url: https://code.usgs.gov/ghsc/esi/groundmotion-processing
  doc_url: https://ghsc.code-pages.usgs.gov/esi/groundmotion-processing/

extra:
  recipe-maintainers:
    - ocefpaf
    - mhearne-usgs
    - cbworden
    - emthompson-usgs
    - gferragu
