{% set version = "1.1.6" %}

package:
  name: gmprocess
  version: {{ version }}

source:
  url: https://github.com/usgs/groundmotion-processing/archive/v{{ version }}.tar.gz
  sha256: 7fe0a0b73adacfb058d8cfd0078e1171fdb463568a572697201556bbac2095c7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - numpy
    - pip ==18.0
  run:
    - python
    - setuptools
    - setuptools_scm
    - {{ pin_compatible('numpy') }}
    - beautifulsoup4
    - cartopy
    - h5py >=2.8.0
    - impactutils
    - libcomcat
    - lxml
    - mapio
    - matplotlib-base
    - obspy >=1.2.1
    - openpyxl
    - openquake.engine >=3.10.1
    - pandas
    - prov
    - ps2ff
    - pyasdf
    - pytest
    - pytz
    - pyyaml
    - requests
    - scipy

test:
  commands:
    - gmprocess --help
    - gmprocess --version
    - gmconvert --help
    - gmsetup --help
    - gmworkspace --help

  imports: 
    - gmprocess

about:
  home: https://github.com/usgs/groundmotion-processing
  license: BSD-3-Clause
  summary: Fetch and process strong motion waveform/peak amplitude data
  license_family: Public Domain
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - mhearne-usgs
    - hschovanec-usgs
    - emthompson-usgs
