{% set version = "0.1.4" %}

package:
  name: gmprocess
  version: {{ version }}

source:
  url: https://github.com/usgs/groundmotion-processing/archive/v{{ version }}.tar.gz
  sha256: d370867bdf11a6774f74f8025e1bf594c67405520bae80fc149a32f864b2f1bc

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python >=3
    - cython
    - numpy
    - pip
  run:
    - python >=3
    - lxml
    - obspy
    - pyyaml
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - gmprocess

about:
  home: https://github.com/usgs/groundmotion-processing
  license: Public Domain
  summary: 'Fetch and process strong motion waveform/peak amplitude data'
  license_family: Public Domain
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - mhearne-usgs
    - hschovanec-usgs
    - emthompson-usgs
