{% set version = "1.1.3" %}

package:
  name: gmprocess
  version: {{ version }}

source:
  url: https://github.com/usgs/groundmotion-processing/archive/v{{ version }}.tar.gz
  sha256: 266091c7c53c4d21d7e9e593b8cd0ad3eb7f533f0d5bfba2c9ca33ac1ab1f59f
  patches:
    - winpi.patch  # [win]

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - gmconvert = gmprocess.bin.gmconvert:main
    - gminfo = gmprocess.bin.gminfo:main
    - gmprocess = gmprocess.bin.gmprocess:main
    - gmsetup = gmprocess.bin.gmsetup:main
    - gmworkspace = gmprocess.bin.gmworkspace:main
    - list_metrics = gmprocess.bin.list_metrics:main

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - numpy
    - pip
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - beautifulsoup4
    - cartopy
    - h5py >=2.8.0
    - impactutils
    - libcomcat
    - lxml
    - mapio
    - matplotlib-base
    - obspy >=1.2.1
    - openpyxl
    - openquake.engine >=3.10.1
    - pandas
    - prov
    - ps2ff
    - pyasdf
    - pytest
    - pytz
    - pyyaml
    - requests
    - scipy

test:
  commands:
    - gmprocess --help
    - gmconvert --help
    - gmsetup --help
    - gmworkspace --help

  imports: 
    - gmprocess

about:
  home: https://github.com/usgs/groundmotion-processing
  license: BSD-3-Clause
  summary: Fetch and process strong motion waveform/peak amplitude data
  license_family: Public Domain
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ocefpaf
    - mhearne-usgs
    - hschovanec-usgs
    - emthompson-usgs
