{% set name = "gmprocess" %}
{% set version = "1.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gmprocess-{{ version }}.tar.gz
  sha256: a8ca8ece8d7d1deef76fabf4b79bfef946dcea0332ac2ab8518df0ff4256dc32

build:
  entry_points:
    - gmconvert = gmprocess.bin.gmconvert:main
    - gminfo = gmprocess.bin.gminfo:main
    - gmrecords = gmprocess.bin.gmrecords:main
    - gmworkspace = gmprocess.bin.gmworkspace:main
    - list_metrics = gmprocess.bin.list_metrics:main
    - cwb_gather = gmprocess.bin.cwb_gather:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<3.11
    - setuptools >=42
    - wheel
    - setuptools-scm >=3.4
    - numpy
    - pip
  run:
    - python >=3.8,<3.11
    - beautifulsoup4 >=4.11
    - configobj >=5.0.6
    - esi-core >=1.0.1
    - esi-utils-colors >1.0
    - esi-utils-io >1.0
    - esi-utils-rupture >1.0
    - folium >=0.12
    - gmpacket >=0.1.0
    - h5py >=2.8
    - lxml >=4.6.1
    - matplotlib-base >=3.1.0
    - numpy >=1.21
    - obspy >=1.4.0
    - openpyxl >=3.0.8
    - openquake.engine >=3.14
    - pandas >=1.0
    - ps2ff >=1.5.2
    - pyasdf >=0.7
    - requests >=2.23
    - ruamel.yaml >=0.17.16
    - schema >=0.7
    - scipy >=1.7
    - setuptools-scm >=6.3.2
    - statsmodels >=0.12.2
    - xlrd >=2.0

test:
  imports:
    - gmprocess
  commands:
    - pip check
    - gmconvert --help
    - gminfo --help
    - gmrecords --help
    - gmworkspace --help
    - list_metrics --help
    - cwb_gather --help
  requires:
    - pip

about:
  home: https://code.usgs.gov/ghsc/esi/groundmotion-processing
  license: Unlicense
  summary:  USGS Automated Ground Motion Processing Software
  license_family: Public Domain
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ocefpaf
    - mhearne-usgs
    - cbworden
    - emthompson-usgs
    - gferragu
