{% set version = "1.2.3" %}

package:
  name: gmprocess
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/50/ca/89687a19690a27ff2445161afc1a33d6e85a3676213b87fbf73e30bfcf39/gmprocess-{{ version }}.tar.gz
  sha256: 9c9786aac6603db3c29d964a35d551b3f3cce384df7a8c9c9ad1e3d018af26b2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - gmconvert = gmprocess.bin.gmconvert:main
    - gminfo = gmprocess.bin.gminfo:main
    - gmrecords = gmprocess.bin.gmrecords:main
    - gmworkspace = gmprocess.bin.gmworkspace:main
    - list_metrics = gmprocess.bin.list_metrics:main
    - cwb_gather = gmprocess.bin.cwb_gather:main

requirements:
  build:
    - python >=3.8
    - pip
    - setuptools-scm >=6.3.2
  run:
    - python >=3.8
    - beautifulsoup4 >=4.11
    - configobj >=5.0.6
    - esi-core >=1.0.1
    - esi-utils-colors >1.0
    - esi-utils-io >1.0
    - esi-utils-rupture >1.0
    - folium >=0.12
    - h5py >=2.8
    - lxml >=4.6.1
    - matplotlib-base >=3.1.0
    - numpy >=1.21
    - obspy >=1.3.0
    - openpyxl >=3.0.8
    - pandas >=1.0
    - ps2ff >=1.5.2
    - pyasdf >=0.7
    - requests >=2.23
    - ruamel.yaml >=0.17.16
    - schema >=0.7
    - scipy >=1.7
    - setuptools-scm >=6.3.2
    - statsmodels >=0.12.2
    - xlrd >=2.0

test:
  commands:
    - gminfo --help
  imports:
    - gmprocess

about:
  home: https://code.usgs.gov/ghsc/esi/groundmotion-processing
  license: LicenseRef-PublicDomain
  summary: 'Parsing and processing ground motion data.'
  license_family: Public Domain
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ocefpaf
    - mhearne-usgs
    - cbworden
    - emthompson-usgs
    - gferragu
