{% set version = "v1.2.2" %}

package:
  name: gmprocess
  version: {{ version }}

source:
  url: https://code.usgs.gov/ghsc/esi/groundmotion-processing/-/archive/{{ version }}/groundmotion-processing-v1.2.2.tar.gz
  sha256: c4aa8566f59a65e37b712bb48207f193d735aad065bcdd8c9ad5f2f270e88e67

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - gmconvert = gmprocess.bin.gmconvert:main
    - gminfo = gmprocess.bin.gminfo:main
    - gmprocess = gmprocess.bin.gmprocess:main
    - gmsetup = gmprocess.bin.gmsetup:main
    - gmworkspace = gmprocess.bin.gmworkspace:main
    - list_metrics = gmprocess.bin.list_metrics:main
    - cwb_gather = gmprocess.bin.cwb_gather:main

requirements:
  build:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - beautifulsoup4>=4.11
    - configobj>=5.0.6
    - esi-core>=1.0.1
    - esi-utils-colors>1.0
    - esi-utils-io>1.0
    - esi-utils-rupture>1.0
    - folium>=0.12
    - h5py>=2.8
    - lxml>=4.6.1
    - matplotlib>=3.1.0
    - numpy>=1.21
    - obspy>=1.3.0
    - openpyxl>=3.0.8
    - pandas>=1.0
    - ps2ff>=1.5.2
    - pyasdf>=0.7
    - requests>=2.23
    - ruamel.yaml>=0.17.16
    - schema>=0.7
    - scipy>=1.7
    - setuptools-scm>=6.3.2
    - statsmodels>=0.12.2
    - xlrd>=2.0

test:
  commands:
    - gmprocess --help
    
  imports:
    - gmprocess

about:
  home: https://code.usgs.gov/ghsc/esi/groundmotion-processing
  license: Public Domain
  summary: 'Parsing and processing ground motion data.'
  license_family: Public Domain
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - mhearne-usgs
    - cbworden
    - emthompson-usgs
    - gferragu