travis:
  secure:
    BINSTAR_TOKEN: tlp2Ha52QPHa/vrTlaiB/v+sbZaWc4e6hDilUPEAAMpvJbsku1WuJb0Kk9gmxrnKlbIV2/UaIZDYv9z/1O4K+zjU5oM+hk9iLXL2y9V8tYtIIKOPoI50PxdwkzW0jZKZpX8F1vLAfwBC3MDwGdmtqxSQLkk5tzXbQaUh1Ye7o1QJjq3L7v1zDwfpXjqPLWrf3V2gxEGf991wFg15Op/cvFF5fUGY2k0CJVfnWGGkT+llMDK1StXHJrnFNOGkdGk8O3upJL8OjQToDVfuUPpbs5Tv3CE8IAseD4KHr9MzaOdPzeEoYz0QqxgMMZnuDir1OFFJoibApEwoR+7inMVlhb519tg9NCWftlSYLk9chrl6ohYPKCfZQFMj5hM+iY7D7eeQKlhi5UpGI2xr5/JnBhV5E4ez9djGyv6dUmzO/FFGt6haeFqmUk9lmOXHpgThdht6mEMWVwJSWqCcntvUskP5rXg12dwuxDO8+NSjd32QPJVFljZlabtDSuGI5ZZo2F+5oNhTn3uHQvMi7h9bBwbW2/rsiDI1QhT1h5t6gLr8BQJ5wISMwrk1vWT9hgDQ8S7MLrX9W/Mwfcic7vNs7pLq2mXdu7QmFyh/KtZt6Z10116MJ/Al6C8Kc/3l1NM8rkhkZvh9lON16CD56EG1+pwCLN5JJdLaL3noXgEPnLU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
